<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Goods;
use Illuminate\Support\Facades\Date;

class GoodsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Goods::insert([
            [
                'us_ID' => 1,
                'g_name' => 'Vintage Vinyl Record Player',
                'g_desc' => 'Classic vintage vinyl record player with modern Bluetooth connectivity.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 250000,
                'g_price_prediction' => 230000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 2,
                'g_name' => 'Limited Edition Sneakers',
                'g_desc' => 'Exclusive limited edition sneakers from a popular brand, rare collector\'s item.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 1000000,
                'g_price_prediction' => 750000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 3,
                'g_name' => 'Smartwatch with Health Tracking',
                'g_desc' => 'Advanced smartwatch with comprehensive health tracking features, perfect for fitness enthusiasts.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 1500000,
                'g_price_prediction' => 1450000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 4,
                'g_name' => 'Bestselling Novel Set',
                'g_desc' => 'Set of bestselling novels by renowned authors, perfect for book lovers.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 75000,
                'g_price_prediction' => 50000,
                'g_age' => rand(1, 5),
                'g_category' => 'Books and Media',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 5,
                'g_name' => 'Collector\'s Edition Action Figure',
                'g_desc' => 'Rare collector\'s edition action figure from a popular movie franchise, mint condition.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 120000,
                'g_price_prediction' => 100000,
                'g_age' => rand(1, 5),
                'g_category' => 'Collectibles',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 6,
                'g_name' => 'Designer Handbag',
                'g_desc' => 'Luxurious designer handbag crafted from premium leather, a timeless fashion statement.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 2000000,
                'g_price_prediction' => 1800000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 7,
                'g_name' => 'Professional DSLR Camera',
                'g_desc' => 'High-performance professional DSLR camera with advanced features, ideal for photography enthusiasts.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 4000000,
                'g_price_prediction' => 3800000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 8,
                'g_name' => 'Vintage Style Dress',
                'g_desc' => 'Elegant vintage-style dress with intricate lace detailing, perfect for special occasions.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 150000,
                'g_price_prediction' => 140000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 9,
                'g_name' => 'Wireless Noise-Canceling Headphones',
                'g_desc' => 'Premium wireless headphones with active noise-canceling technology, immersive sound experience.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 180000,
                'g_price_prediction' => 150000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 10,
                'g_name' => 'Classic Polaroid Camera',
                'g_desc' => 'Iconic classic Polaroid camera, instant vintage-style photos with modern features.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 520000,
                'g_price_prediction' => 500000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 1,
                'g_name' => 'Wireless Charging Pad',
                'g_desc' => 'Sleek and stylish wireless charging pad compatible with various smartphone models.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 500000,
                'g_price_prediction' => 480000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 2,
                'g_name' => 'Vintage Leather Jacket',
                'g_desc' => 'Classic vintage leather jacket with timeless style and rugged durability.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 200000,
                'g_price_prediction' => 190000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 3,
                'g_name' => 'Smart Home Security Camera',
                'g_desc' => 'Advanced smart home security camera with AI-powered motion detection and night vision.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 12000000,
                'g_price_prediction' => 11000000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 4,
                'g_name' => 'Wireless Gaming Mouse',
                'g_desc' => 'Ergonomic wireless gaming mouse with customizable RGB lighting and high precision sensor.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 400000,
                'g_price_prediction' => 380000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 5,
                'g_name' => 'Fitness Tracker Smartwatch',
                'g_desc' => 'Smartwatch with built-in fitness tracker, heart rate monitor, and sleep analysis features.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 6000000,
                'g_price_prediction' => 5700000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 6,
                'g_name' => 'Vintage Retro Turntable',
                'g_desc' => 'Classic vintage retro turntable with built-in speakers for vinyl record playback.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 100000,
                'g_price_prediction' => 95000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 7,
                'g_name' => 'Portable Espresso Maker',
                'g_desc' => 'Compact and portable espresso maker for coffee lovers on the go, compatible with Nespresso capsules.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 800000,
                'g_price_prediction' => 750000,
                'g_age' => rand(1, 5),
                'g_category' => 'Kitchenware',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 8,
                'g_name' => 'Graphic Design Software Bundle',
                'g_desc' => 'Bundle of professional graphic design software tools for creating stunning digital artwork and illustrations.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 200000,
                'g_price_prediction' => 190000,
                'g_age' => rand(1, 5),
                'g_category' => 'Tools and Equipment',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 9,
                'g_name' => 'Vintage Retro Camera',
                'g_desc' => 'Classic vintage retro camera with manual film advance and authentic vintage aesthetic.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 1200000,
                'g_price_prediction' => 1100000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 10,
                'g_name' => 'Smart LED Light Bulbs',
                'g_desc' => 'Smart LED light bulbs with adjustable color temperature and smartphone app control.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 300000,
                'g_price_prediction' => 280000,
                'g_age' => rand(1, 5),
                'g_category' => 'Home Decor',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 1,
                'g_name' => 'Bluetooth Portable Speaker',
                'g_desc' => 'Compact and portable Bluetooth speaker with powerful sound output and long battery life.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 500000,
                'g_price_prediction' => 480000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 2,
                'g_name' => 'Vintage Leather Backpack',
                'g_desc' => 'Classic vintage leather backpack with multiple compartments and adjustable shoulder straps.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 150000,
                'g_price_prediction' => 140000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 3,
                'g_name' => 'Portable Power Bank Charger',
                'g_desc' => 'Compact and lightweight portable power bank charger with fast charging technology.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 200000,
                'g_price_prediction' => 190000,
                'g_age' => rand(1, 5),
                'g_category' => 'Electronics',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 4,
                'g_name' => 'Complete Guitar Starter Kit',
                'g_desc' => 'Everything you need to start learning guitar, including a guitar, accessories, and instructional materials.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 500000,
                'g_price_prediction' => 480000,
                'g_age' => rand(1, 5),
                'g_category' => 'Musical Instruments',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 5,
                'g_name' => 'Limited Edition Vinyl Records',
                'g_desc' => 'Rare limited edition vinyl records featuring classic albums from iconic artists.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 800000,
                'g_price_prediction' => 750000,
                'g_age' => rand(1, 5),
                'g_category' => 'Collectibles',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 6,
                'g_name' => 'Home Tool Set',
                'g_desc' => 'Comprehensive home tool set with various essential tools for DIY projects and repairs.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 1000000,
                'g_price_prediction' => 950000,
                'g_age' => rand(1, 5),
                'g_category' => 'Tools and Equipment',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 7,
                'g_name' => 'Fitness Resistance Bands Set',
                'g_desc' => 'Set of high-quality fitness resistance bands for strength training and rehabilitation exercises.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 200000,
                'g_price_prediction' => 190000,
                'g_age' => rand(1, 5),
                'g_category' => 'Sports and Fitness Equipment',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 8,
                'g_name' => 'Healthy Recipe Cookbook',
                'g_desc' => 'Collection of healthy and delicious recipes for everyday meals, promoting a balanced diet.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 30000,
                'g_price_prediction' => 28000,
                'g_age' => rand(1, 5),
                'g_category' => 'Books and Media',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 9,
                'g_name' => 'Professional Chef Knife Set',
                'g_desc' => 'Premium chef knife set with high-quality blades and ergonomic handles, essential for culinary enthusiasts.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 150000,
                'g_price_prediction' => 140000,
                'g_age' => rand(1, 5),
                'g_category' => 'Kitchenware',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 10,
                'g_name' => 'Vintage Vinyl Records Collection',
                'g_desc' => 'Collection of vintage vinyl records featuring classic albums from various artists.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 1200000,
                'g_price_prediction' => 1100000,
                'g_age' => rand(1, 5),
                'g_category' => 'Musical Instruments',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 1,
                'g_name' => 'Portable Espresso Maker',
                'g_desc' => 'Compact and portable espresso maker for coffee lovers on the go, compatible with Nespresso capsules.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 800000,
                'g_price_prediction' => 750000,
                'g_age' => rand(1, 5),
                'g_category' => 'Kitchenware',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 2,
                'g_name' => 'DIY Home Improvement Book',
                'g_desc' => 'Comprehensive guidebook for DIY home improvement projects, step-by-step instructions for various tasks.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 25000,
                'g_price_prediction' => 23000,
                'g_age' => rand(1, 5),
                'g_category' => 'Books and Media',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 3,
                'g_name' => 'Vintage Vinyl Records Collection (MLTR)',
                'g_desc' => 'Collection of vintage vinyl records featuring classic albums from various artists.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 1200000,
                'g_price_prediction' => 1000000,
                'g_age' => rand(1, 5),
                'g_category' => 'Musical Instruments',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 4,
                'g_name' => 'Artisan Handcrafted Vase',
                'g_desc' => 'Handcrafted ceramic vase with intricate designs, perfect for adding elegance to any home decor.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 50000,
                'g_price_prediction' => 45000,
                'g_age' => rand(1, 5),
                'g_category' => 'Home Decor',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 5,
                'g_name' => 'Rare Collectible Coin Set',
                'g_desc' => 'Set of rare collectible coins from various historical periods, a valuable addition to any coin collection.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 100000,
                'g_price_prediction' => 95000,
                'g_age' => rand(1, 5),
                'g_category' => 'Collectibles',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 6,
                'g_name' => 'Professional Power Drill Set',
                'g_desc' => 'Complete power drill set with various drill bits and accessories, essential for DIY projects and home improvements.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 800000,
                'g_price_prediction' => 750000,
                'g_age' => rand(1, 5),
                'g_category' => 'Tools and Equipment',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 7,
                'g_name' => 'Designer Handcrafted Scarf',
                'g_desc' => 'Luxurious designer scarf handcrafted from premium silk, featuring exquisite patterns and vibrant colors.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 60000,
                'g_price_prediction' => 55000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 8,
                'g_name' => 'Antique Brass Table Lamp',
                'g_desc' => 'Antique brass table lamp with ornate details, adding a touch of vintage charm to any room.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 7000000,
                'g_price_prediction' => 6500000,
                'g_age' => rand(1, 5),
                'g_category' => 'Home Decor',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 9,
                'g_name' => 'Vintage Toolbox Set',
                'g_desc' => 'Vintage toolbox set with retro design, perfect for collectors or as a decorative piece in a workshop or garage.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 400000,
                'g_price_prediction' => 380000,
                'g_age' => rand(1, 5),
                'g_category' => 'Tools and Equipment',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 10,
                'g_name' => 'Limited Edition Designer Watch',
                'g_desc' => 'Exclusive limited edition designer watch with intricate craftsmanship and premium materials.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 3000000,
                'g_price_prediction' => 2800000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 1,
                'g_name' => 'Vintage Record Player',
                'g_desc' => 'Classic vintage record player with retro design, perfect for vinyl enthusiasts and collectors.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 1200000,
                'g_price_prediction' => 110000,
                'g_age' => rand(1, 5),
                'g_category' => 'Collectibles',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 2,
                'g_name' => 'Vintage Style Wall Clock',
                'g_desc' => 'Vintage style wall clock with antique finish, adds character and charm to any living space.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 5000000,
                'g_price_prediction' => 400000,
                'g_age' => rand(1, 5),
                'g_category' => 'Home Decor',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],
            [
                'us_ID' => 3,
                'g_name' => 'Vintage Leather Backpack (Blue)',
                'g_desc' => 'Classic vintage leather jacket with timeless style and rugged durability.',
                'g_type' => rand(0, 1) ? 'Used' : 'New',
                'g_original_price' => 200000,
                'g_price_prediction' => 190000,
                'g_age' => rand(1, 5),
                'g_category' => 'Clothing and Accessories',
                'created_at' => Date::now(),
                'updated_at' => Date::now(),
            ],

        ]);
    }


}
