<?php

namespace Database\Seeders;

use App\Constants\Roles;
use Illuminate\Database\Seeder;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Raja Solomon Fukel',
                'us_username'           => 'rajasol',
                'us_email'              => 'rajasol@gmail.com',
                'password'              => Hash::make('Minyons123_'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Male',
                'us_city'               => 'Jakarta',
                'us_province'           => 'DKI Jakarta',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Elia Yenny',
                'us_username'           => 'eliayen',
                'us_email'              => 'eliayen@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Female',
                'us_city'               => 'Jakarta',
                'us_province'           => 'DKI Jakarta',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Budi Yono',
                'us_username'           => 'budiyono',
                'us_email'              => 'budiyono@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Male',
                'us_city'               => 'Bekasi',
                'us_province'           => 'Jawa Barat',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Christiana Tjitradinata',
                'us_username'           => 'christiaza',
                'us_email'              => 'christiaza@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Female',
                'us_city'               => 'Medan',
                'us_province'           => 'Sumatera Utara',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Christian Robert',
                'us_username'           => 'christianrob',
                'us_email'              => 'christianrob@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Male',
                'us_city'               => 'Kabupaten Bekasi',
                'us_province'           => 'Jawa Barat',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Joy Friska Saragih',
                'us_username'           => 'joyffriska',
                'us_email'              => 'joyffriska@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2006-01-16',
                'us_gender'             => 'Female',
                'us_city'               => 'Kabupaten Bekasi',
                'us_province'           => 'Jawa Barat',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Felda Everyl',
                'us_username'           => 'feldaeve',
                'us_email'              => 'feldaeve@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Female',
                'us_city'               => 'Jakarta Utara',
                'us_province'           => 'DKI Jakarta',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Laura Purba',
                'us_username'           => 'laurapurba',
                'us_email'              => 'laurapurba@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Female',
                'us_city'               => 'Kota Jakarta Utara',
                'us_province'           => 'DKI Jakarta',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Winda Prastika Johan',
                'us_username'           => 'windajohan',
                'us_email'              => 'windajohan@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Female',
                'us_city'               => 'Jakarta Utara',
                'us_province'           => 'DKI Jakarta',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'role_id'               => Roles::ROLE_USER,
                'us_name'               => 'Vony Renfia',
                'us_username'           => 'vonyren',
                'us_email'              => 'vonyren@gmail.com',
                'password'              => Hash::make('Minyons123.'),
                'password_updated_at'   => now(),
                'us_DOB'                => '2003-01-01',
                'us_gender'             => 'Female',
                'us_city'               => 'Kota Jakarta Pusat',
                'us_province'           => 'DKI Jakarta',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
        ]);
    }
}
